# Generated by Django 3.2.25 on 2024-06-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('underwater', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('Turbidity', 'Turbidity'), ('Temperature', 'Temperature'), ('pH', 'pH'), ('Dissolved Oxygen', 'Dissolved Oxygen'), ('Conductivity', 'Conductivity'), ('Ammonia Nitrogen', 'Ammonia Nitrogen'), ('Nitrogen', 'Nitrogen'), ('Phosphorus', 'Phosphorus'), ('Permanganate', 'Permanganate')], max_length=20)),
                ('battery_level', models.PositiveIntegerField()),
                ('next_maintenance_date', models.DateTimeField()),
                ('warranty_expiration_date', models.DateField()),
                ('start_date', models.DateField()),
            ],
        ),
    ]
