# Generated by Django 4.2 on 2024-06-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("underwater", "0002_sensor"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaterQualityDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("province", models.CharField(max_length=100)),
                ("river_basin", models.CharField(max_length=100)),
                ("section_name", models.CharField(max_length=100)),
                ("monitoring_time", models.DateTimeField(blank=True, null=True)),
                ("water_quality_category", models.CharField(blank=True, max_length=10)),
                ("water_temperature", models.FloatField(blank=True, null=True)),
                ("pH", models.FloatField(blank=True, null=True)),
                ("dissolved_oxygen", models.FloatField(blank=True, null=True)),
                ("conductivity", models.FloatField(blank=True, null=True)),
                ("turbidity", models.FloatField(blank=True, null=True)),
                ("permanganate_index", models.FloatField(blank=True, null=True)),
                ("ammonia_nitrogen", models.FloatField(blank=True, null=True)),
                ("total_phosphorus", models.FloatField(blank=True, null=True)),
                ("total_nitrogen", models.FloatField(blank=True, null=True)),
                ("chlorophyll_a", models.FloatField(blank=True, null=True)),
                ("algae_density", models.FloatField(blank=True, null=True)),
                ("site_status", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
