# Generated by Django 4.2 on 2024-06-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ohio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("temp_c", models.FloatField(blank=True, null=True)),
                ("river", models.CharField(blank=True, default="", max_length=100)),
                ("conductivity", models.FloatField(blank=True, null=True)),
                (
                    "common_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "latin_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("phylo_num", models.IntegerField(blank=True, null=True)),
                ("count", models.IntegerField(blank=True, null=True)),
                (
                    "_3cm_size_class",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("length_cm", models.FloatField(blank=True, null=True)),
                ("weight_kg", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
