# Generated by Django 4.2 on 2024-06-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ohio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_3cm_Size_Class", models.CharField(max_length=50)),
                ("weight_kg", models.FloatField()),
                ("latin_name", models.CharField(max_length=50)),
            ],
        ),
    ]
