# Generated by Django 4.1 on 2024-04-29 17:16

from django.db import migrations, models
import login.models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userinfo",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterModelManagers(
            name="userinfo",
            managers=[
                ("objects", login.models.CustomUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="mail",
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
