# Generated by Django 4.2 on 2024-06-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WaterQuality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("province", models.CharField(max_length=100, verbose_name="省份")),
                ("watershed", models.CharField(max_length=100, verbose_name="流域")),
                ("section_name", models.CharField(max_length=100, verbose_name="段面名称")),
                ("monitoring_time", models.DateTimeField(verbose_name="监测时间")),
                (
                    "water_quality_category",
                    models.CharField(max_length=50, verbose_name="水质类别"),
                ),
                ("water_temperature", models.FloatField(verbose_name="水温(℃)")),
                ("ph", models.FloatField(verbose_name="pH值")),
                ("dissolved_oxygen", models.FloatField(verbose_name="溶解氧(mg/L)")),
                ("conductivity", models.FloatField(verbose_name="电导率(μS/cm)")),
                ("turbidity", models.FloatField(verbose_name="浊度(NTU)")),
                ("permanganate_index", models.FloatField(verbose_name="高锰酸盐指数(mg/L)")),
                ("ammonium_nitrogen", models.FloatField(verbose_name="氨氮(mg/L)")),
                ("total_phosphorus", models.FloatField(verbose_name="总磷(mg/L)")),
                ("total_nitrogen", models.FloatField(verbose_name="总氮(mg/L)")),
                ("chlorophyll", models.FloatField(verbose_name="叶绿素(mg/L)")),
                ("algae_density", models.FloatField(verbose_name="藻密度(cells/mL)")),
                (
                    "station_condition",
                    models.CharField(blank=True, max_length=200, verbose_name="站点情况"),
                ),
            ],
            options={
                "verbose_name": "水质监测数据",
                "verbose_name_plural": "水质监测数据",
            },
        ),
    ]
