# Generated by Django 4.2 on 2024-06-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maininfo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="waterquality",
            name="algae_density",
            field=models.FloatField(null=True, verbose_name="藻密度(cells/mL)"),
        ),
        migrations.AlterField(
            model_name="waterquality",
            name="ammonium_nitrogen",
            field=models.FloatField(null=True, verbose_name="氨氮(mg/L)"),
        ),
        migrations.AlterField(
            model_name="waterquality",
            name="chlorophyll",
            field=models.FloatField(null=True, verbose_name="叶绿素(mg/L)"),
        ),
        migrations.AlterField(
            model_name="waterquality",
            name="conductivity",
            field=models.FloatField(null=True, verbose_name="电导率(μS/cm)"),
        ),
        migrations.AlterField(
            model_name="waterquality",
            name="dissolved_oxygen",
            field=models.FloatField(null=True, verbose_name="溶解氧(mg/L)"),
        ),
        migrations.AlterField(
            model_name="waterquality",
            name="monitoring_time",
            field=models.DateTimeField(null=True, verbose_name="监测时间"),
        ),
        migrations.AlterField(
            model_name="waterquality",
            name="permanganate_index",
            field=models.FloatField(null=True, verbose_name="高锰酸盐指数(mg/L)"),
        ),
        migrations.AlterField(
            model_name="waterquality",
            name="ph",
            field=models.FloatField(null=True, verbose_name="pH值"),
        ),
        migrations.AlterField(
            model_name="waterquality",
            name="total_nitrogen",
            field=models.FloatField(null=True, verbose_name="总氮(mg/L)"),
        ),
        migrations.AlterField(
            model_name="waterquality",
            name="total_phosphorus",
            field=models.FloatField(null=True, verbose_name="总磷(mg/L)"),
        ),
        migrations.AlterField(
            model_name="waterquality",
            name="turbidity",
            field=models.FloatField(null=True, verbose_name="浊度(NTU)"),
        ),
        migrations.AlterField(
            model_name="waterquality",
            name="water_temperature",
            field=models.FloatField(null=True, verbose_name="水温(℃)"),
        ),
    ]
