# Generated by Django 4.2 on 2024-06-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maininfo", "0002_alter_waterquality_algae_density_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="waterquality",
            name="water_quality_category",
            field=models.CharField(max_length=50, null=True, verbose_name="水质类别"),
        ),
    ]
