# Generated by Django 4.2 on 2024-06-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maininfo", "0003_alter_waterquality_water_quality_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaterQualityRecordForMonth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("province", models.CharField(max_length=50)),
                ("basin", models.CharField(max_length=50)),
                ("section_name", models.CharField(max_length=100)),
                ("monitoring_time", models.DateTimeField(blank=True, null=True)),
                ("water_category", models.CharField(blank=True, max_length=50)),
                ("water_temperature", models.CharField(max_length=50)),
                ("ph", models.CharField(max_length=50)),
                ("dissolved_oxygen", models.CharField(max_length=50)),
                ("electrical_conductivity", models.CharField(max_length=50)),
                ("turbidity", models.CharField(max_length=50)),
                ("permanganate_index", models.CharField(max_length=50)),
                ("ammonia_nitrogen", models.CharField(max_length=50)),
                ("total_phosphorus", models.CharField(max_length=50)),
                ("total_nitrogen", models.CharField(max_length=50)),
                ("chlorophyll_a", models.CharField(max_length=50)),
                ("algal_density", models.CharField(max_length=50)),
                ("site_condition", models.CharField(max_length=100)),
            ],
        ),
    ]
