# Generated by Django 4.2 on 2024-06-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterQualityPredict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TEMP', models.FloatField()),
                ('PH', models.FloatField()),
                ('DO', models.FloatField()),
                ('Cond', models.FloatField()),
                ('NTU', models.FloatField()),
                ('Mn', models.FloatField()),
                ('NH3', models.FloatField()),
            ],
        ),
    ]
